name: SSH into our runners

on:
  push:
    branches:
      - ping_author_2

jobs:
  ssh_runner:
    name: "SSH"
    runs-on: ubuntu-22.04
    env:
      github_actor: ydshieh
    steps:
      - name: Store Slack infos
        shell: bash
        run: |
          echo "${{ env.github_actor }}"
          echo ${{ secrets[format('{0}_{1}', env.github_actor ,SLACK_ID)] }}

#      - name: Store Slack infos
#        shell: bash
#        run: |
#          echo ${{ env.SLACKCHANNEL }}
#          python -c 'import os; o = os.environ["SLACKCHANNEL"][:8]; print(o)'